[gcp_service_account]
type = "service_account"
project_id = "electrical-data-viewer-467304"
private_key_id = "d51d42072089acf55f73a15e2582bf8720da75dd"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCaI2IJFCp+KE5R
RRzMYE88d2FQPxrj9lkWsd/01T6koGibGzg8PQSNNd5ZeJtA6LwJ6Rw29Bfa0rkU
vJ2Rhaj6mG9z108A+URI90MBFjM+tW7BjHX35qz2wL6hZM71xHnhzQV/Nmy9kLuZ
TqUMYIkKKopQyFu5FjKDROmtyTGLBokjimBxKBgaM/aP6gHaDXFkq+BMaJT9PoYo
Oggu4w1kqAqyF6EUPL2RSV8IXB2OZHrc906yVO+zp6UvpFoT8u6ECK6HpSHjZPqq
I80VmJqc6kq6caqiUoMqtjlHzHQYQIIxmRpalZklnLNZTUXRR2KHFB7aTKeriEhA
kkeh+3gNAgMBAAECggEAChP4K/nKkXcXL88iA+bkJ2Ly1OlbW75Wstosd3id4Ouw
CzwrYBzpOEZmZFkzZXoSGV/JfXpWOPOAMG/oqYQguUnQN7XDL6Acq9ym3+JQtW/t
bvA9IllNw9B0Zl8N/Rm8klvyWQ/46igVa/+tYPLK4wRHCOMgxChEYzrVQIygFaPc
t+l1QBmgDVnm8kDRi1VMxT+p8sBNmKQBqGHR58kRssDVdQrtr0AUSySU5ZeMox3J
H8uK1BRb72+j+NgXG/rIuJDKW86C9uI88X1VvcaoIJYe8eVQnJmPcPMl+Pm7mNGN
9k/ZcBSiQX2tl+2BHhQ2vRuKRV/ke/sbYJHufm3cjQKBgQDUzu92ZOyzkXF4ZRlS
hGgjfuI7wdM4smF60ShLZHHsdshIN9pJQ9FxhDCuWHkIT5z/bVG2cmmD4jI5v0tC
BnPa56mQcvGv0bFV8eF+E7Yz/4bmiN4zDn0KOn8Tic7fVIAoWwIIgVi/WRJdEyIx
FH6dMftPZjyt7uzyieby6TsQuwKBgQC5bBLee+ZPJcSQ6tga7FPeNGJGa72qnocd
mS0zw2TK6NLm/O9VpxdD+PhtKrFNmmZx164KgF8VUnhDUnj/6YmMsIjDWtjrFd8l
mjEHbaMyvjtzfKhoG+s3beFNC7vy4xuIREpBOqy62DG7kAFRV48wbtRhtcUvdBpT
4XybnYwR1wKBgCI+koYow3Y551qKWkLPD7r2hg07qXOsMMeEtMk9BqAYlS4Z3sR/
Z0qvDO5hSkiuFwN7YfTMAHK6iX6Fa+TaCPam5MBb3sx+H91GqRSSs3U2n0ylpavt
nu1wcFaCjImfnWfhDTi1J8TS3oOfupbPR3igPGKQfx82HWcCDen04g5VAoGAe92a
bU3PeKf+O+DmJHYjQJk13V00ArqMAFXHQIES4AnQecYWC93nSN0U97hBYVn3fa1a
8mD3I8NH25FIi4xy+q0jb31M0x51RyVOA2xWTRuPk4J+7a1Y4Fpi25kvIP5d8hXM
lO6hXN/3uRhmCPS5Dt26uts2spCY1dgX6czBOVkCgYB2he4+PA/+WO3zWSEok+gb
anq5kv2cbqfv6gZvXnZtGfUuh43xSgm/uw538wILNHyyfKKi30qZZ9rE7vH35AB/
z47PJhRQWFF90OA4b0aQcNlqZwBSYHYMOqzhFFplv+RlWotKXqEncS+bIKpiyJ9O
cxuZ9S5aS6731Yepu+r+FQ==
-----END PRIVATE KEY-----"""
client_email = "streamlit-editor@electrical-data-viewer-467304.iam.gserviceaccount.com"
client_id = "115637566166616104373"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-editor@electrical-data-viewer-467304.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
